### ISSUE TITLE
Will vehicles stay flat? How will vehicles deal with non flat world geometry?

### ISSUE THREAD

**Issue by macsforme** [TeamChillax/design#1]
Taken from @JeffM2501's original document:

This is known as the tilting tank issue. In BZFlag, tanks are flat. There are many reasons for this; mainly, it's simple and it allows gameplay to be fun without turret aiming.

If we allow tanks to tilt, we have to solve the following problems:

How do people aim the guns when on a slope? The obvious solution is to allow some form of weapon rotation. Failure to allow some form of aiming will make it very hard to to line up shots when on a slope.

If we allow tanks to tilt, we also have to deal with how tanks fall off ledges. Do we allow them to flip over? If we do how do players get right side up again? Do we do a hybrid method where tanks can tilt from the ground, but not from a ledge?

**Comment by macsforme** [comment]
I am in favor of keeping tanks flat at all times. Changing this would result in a significantly different game concept than what BZFlag is.

An useful enhancement might be to allow map makers to define certain sloped surfaces as "climbable," which would then allow tanks to ascend them at a speed inversely proportional to their slope (visually, the tank's jump jets could wholly or partially activate while doing this, and the same effect could be used when a tank is hovering at the extreme edge of an object, creating a more realistic appearance). I feel that this would be an appropriate enhancement/evolution of the BZFlag game concept without making it an inherently different game.

**Comment by JeffM2501** [comment]
You would not need to flag things are ramps, just set a max angle that can be traversed and the physics system can do the rest for you.

What part of the tank is in contact with the ramp? There are several options? Is the problem of tilting just one of aiming or flipping? There are options to solve both of those issues.

Here is an image showing the possible contact point and rotation options for a simplified ramp, and what problems the "keep it flat" cases will have.

![tiltingtankage](https://cloud.githubusercontent.com/assets/322174/17488233/3a844d7a-5d4d-11e6-91d6-bed75c5b93d1.png)

**Comment by JeffM2501** [comment]
![slopechoices](https://cloud.githubusercontent.com/assets/322174/17503748/2638f96a-5da7-11e6-8ad3-91f6c8f5ad91.png)

**Comment by JeffM2501** [comment]
Initial consensus is to leave tanks flat and cheat graphically for visuals and do some experiments with traction computations for motion during development
