### ISSUE TITLE
Will weapons be able to rotate separate from the vehicle (tilt, rotation, tilt and rotation)?

### ISSUE THREAD

**Issue by macsforme** [TeamChillax/design#2]
Taken from @JeffM2501's original document:

Allowing vertical aiming does solve many problems with allowing vehicles to tilt, and adds a different dimension to the game. It does bring up additional requirements, namely in the realm of input.

Allowing aiming of any axis will require a second set of input axes. Right now BZFlag gets away with a single set of axes, X and Y. This means it can be played with one hand, keyboard or mouse. Adding aiming will mean at least 3 axes will be needed, X and Y for driving, and Z for aiming.

Most games solve this by having players use 2 hands: motion on one, aiming on another. This is most commonly implemented as a mouse/keyboard combination. Of the two input devices the mouse has much more granularity than the keyboard (it is effectively an analog control). For this reason, most players will prefer to have the axes that affect the shot direction assigned to the mouse. This means steering and vertical aiming on the mouse, and forward/backward motion on the keyboard.

There are of course alternative inputs, like a gamepad, that will be a fine solution. Some people have suggested other alternate inputs, such as using the mouse wheel for vertical aiming, or various "up/down" keys to move the turret. While these may be possible, they will not offer the speed and precision of a mouse. We need to take this all into account when thinking about this feature.

Turret rotation adds an additional axis, so it compounds the issue further. Additionally if we assume that we will want the camera to be aligned with the weapons system (for aiming), then we have cases where people can't see where they are driving. This may be a desirable trade off, but we should investigate its frustration level. Perhaps the system would need driving modes, or controls to quickly align the vehicle to the camera.

**Comment by macsforme** [comment]
I am in favor of keeping tank turrets fixed. There are plenty of tank games with more complicated controls, but BZFlag was attractive with its simple controls because that "limitation" allowed you to overcome your opponents with more creative firing (firing shots rapidly in series, using shot ricochets, etc.). It was also nice that you could play the game on a laptop keyboard without having to also plug in a mouse or use the trackpad. Changing this would cause us to end up with a significantly different game.

**Comment by JeffM2501** [comment]
You can have a compromise. Let the tanks tilt, but have the turrets rotate to compensate. So the GUN is always flat. that may look better graphically and still give the simpler game play.

Your max ramp angle would be defined based on how far the turret could tilt up/down.

**Comment by JeffM2501** [comment]
![slopechoices](https://cloud.githubusercontent.com/assets/322174/17503748/2638f96a-5da7-11e6-8ad3-91f6c8f5ad91.png)

**Comment by JeffM2501** [comment]
Shots will stay "flat" for simplicity. Initial consensus is to leave tanks flat and cheat graphically for visuals and do some experiments with traction computations for motion during development.
