### ISSUE TITLE
Should tanks jump?

### ISSUE THREAD

**Issue by macsforme** [TeamChillax/design#3]
Taken from @JeffM2501's original document:

Jumping has the fewest questions and ramifications. It is mainly a gameplay choice and will only really affect map design.

**Comment by macsforme** [comment]
Yes, I think we should include jumping in the game, and leave it as a configuration option that can be turned off for certain style preferences (a lot of hard-core players use non-jumping maps for an experience more dependent on, and illustrative of, precise aiming and dodging skills, so we would want to continue making that experience available).

**Comment by JeffM2501** [comment]
It was pointed out that this may also be related to tilting/ramps issue #1. If the tanks are not kept flat, how does it affect the jump vector? is it still pure Z+? or is it normal to the surface you are on?

How is the jump vector computed? WHat does the jump represent, a fixed explosion or some kind of controllable jet?
An explosion is like a fixed force vector ( you always jump the same height?)
As a jet or rocket it changes some things (Do you only go up when you hit  your thrust key?, how does it affect falling?)

Also what about the amount of control you have in the air? If we are saying they are jets, some amount of air control could be expected (abet at a much slower speed)

I have seen a demo where jumping was handled by a "jump power" bar that filled up over time. So you could quickly do a number of small jumps, but would have to hold the bar for a larger/longer jump. Then the power refueled slowly over time. That may offer an interesting minor variation on what bzflag does.

**Comment by JeffM2501** [comment]
Since tanks will be staying flat for the forseeble design #1, #2 jumping will be in. Experiments at dev time will determine best method of jumping.
