### ISSUE TITLE
Should there be dynamic world geometry/doors?

### ISSUE THREAD

**Issue by macsforme** [TeamChillax/design#5]
Taken from @JeffM2501's original document:

If we want to do this, it will require some choices for our 3D engine (rendering and lighting), simulation, networking, and physics systems. The answer to this helps set up requirements for those systems.

**Comment by macsforme** [comment]
While this would be interesting, additional complexity does not always make for a better experience, and I feel like dynamic geometry would be more suited to a different game concept. While there are physics engines that readily support such a feature, it raises a lot of questions about how gameplay would be affected, opens up a strong possibility for a degraded user experience due to misuse of this feature in low-quality maps, potentially raises the system requirements for additional processing time required for these objects, and creates additional synchronized state concerns. I am therefore in favor of all geometry in the game being static.

**Comment by JeffM2501** [comment]
This is something that could be added later in a protocol breaking update, so I agree it can be left out of the first run.

We just need to set our initial expectations.

**Comment by JeffM2501** [comment]
Consensus is to leave this for later and not include it in the initial design.
