### ISSUE TITLE
Should there be local physics override on world geometry (like BZFlag's physics drivers)?

### ISSUE THREAD

**Issue by macsforme** [TeamChillax/design#7]
From @JeffM2501's original document:

This has the same concerns as dynamic world geometry (#5).

**Comment by macsforme** [comment]
While physics drivers were interesting in BZFlag, they were not too widely used and there were some complications to using them. You had to tune them carefully to make the do what you wanted, it was easy to get caught or stuck on other geometry as you got bounced around, and the behavior of shells fired while the shooter was moving at high speed from a physics driver was odd. We would additionally have to be concerned about the effects of these things on the physics simulation (doable, but could complicate testing quite a bit) as well as possibly a way to animate them so it would be clearer what they do. Due to these complications, and because I believe these features had only a limited contribution to what made BZFlag fun, I am in favor of excluding this feature from the new game.

**Comment by allejo** [comment]
With BZFlag, death objects are handled by physics drivers, which I believe should be included to allow map makers to mark certain areas as "off-limits" like a river or an generator. As for general physics, trampolines and speed ramps are probably the most common uses in BZFlag. Popular maps have made use of both; to name a few: Missile Wars 2.3, Two Tanks, Bloodbath.

**Comment by JeffM2501** [comment]
Those can easily be properties of a volume. We can define whatever properties we choose to implement.

**Comment by JeffM2501** [comment]
Issues from this discussion have been includes in the game-play design document.
